### ISSUE TITLE
fix: 网页reader可以正常使用，idea插件报错

### ISSUE THREAD

**Issue by dnslin** [nancheung/legado-reader#21]
获取书架列表失败

java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "books" is null
	at com.nancheung.plugins.jetbrains.legadoreader.dao.Data.setBookshelf(Data.java:111)
	at com.nancheung.plugins.jetbrains.legadoreader.toolwindow.IndexUI.lambda$refreshBookshelf$2(IndexUI.java:120)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by nancheung** [comment]
reader哪个版本？

**Comment by dnslin** [comment]
最新版本
