### ISSUE TITLE
V1.4.1版本异常反馈

### ISSUE THREAD

**Issue by NBXianYu** [nancheung/legado-reader#22]
试了几次会卡死的情况，idea有四种错误日志反馈。
重现步骤：
看小说中，点下一章，加载失败，然后返回到书架目录去，去点击刚才看的小说，这个时候页面卡死。

另外，希望能优化一下点下一章功能，经常加载不出来，可以的话，章节页面加一个刷新按钮，加载失败的时候能点，不用再返回目录再点小说。。。感谢大佬。
`
异常一：
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.nancheung.plugins.jetbrains.legadoreader.action.ShowBookInfoAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.nancheung.plugins.jetbrains.legado-reader]
    at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
    at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
    at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
    at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
    at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:200)

异常二：

java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 1 out of bounds for int[0]
    at java.base/java.lang.System.arraycopy(Native Method)
    at java.desktop/javax.swing.text.BoxView.updateLayoutArray(BoxView.java:215)
    at java.desktop/javax.swing.text.BoxView.replace(BoxView.java:190)
    at java.desktop/javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:597)
    at java.desktop/javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:503)
    at java.desktop/javax.swing.text.FlowView.layout(FlowView.java:209)
    at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
    at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
    at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
    at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
    at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1826)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1107)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1085)
    at java.desktop/javax.swing.text.DefaultCaret.setVisible(DefaultCaret.java:1011)
    at java.desktop/com.apple.laf.AquaCaret.setVisible(AquaCaret.java:79)
    at java.desktop/com.apple.laf.AquaCaret.fireStateChanged(AquaCaret.java:85)
    at java.desktop/javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1313)
    at java.desktop/javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1212)
    at java.desktop/javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1193)
    at java.desktop/javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1090)
    at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1691)
    at com.nancheung.plugins.jetbrains.legadoreader.toolwindow.IndexUI.lambda$setTextBodyUIData$10(IndexUI.java:306)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

异常三：
获取正文内容失败

java.lang.NullPointerException: Cannot invoke "javax.swing.text.View.getMaximumSpan(int)" because "v" is null
    at java.desktop/javax.swing.text.BoxView.layoutMinorAxis(BoxView.java:838)
    at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:345)
    at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
    at java.desktop/javax.swing.text.FlowView.layout(FlowView.java:228)
    at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
    at java.desktop/javax.swing.text.BoxView.updateChildSizes(BoxView.java:367)
    at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:349)
    at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:709)
    at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1826)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1107)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1085)
    at java.desktop/javax.swing.text.DefaultCaret.setVisible(DefaultCaret.java:1011)
    at java.desktop/com.apple.laf.AquaCaret.setVisible(AquaCaret.java:79)
    at java.desktop/com.apple.laf.AquaCaret.fireStateChanged(AquaCaret.java:85)
    at java.desktop/javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1313)
    at java.desktop/javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1212)
    at java.desktop/javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1193)
    at java.desktop/javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1090)
    at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1691)
    at com.nancheung.plugins.jetbrains.legadoreader.toolwindow.IndexUI.lambda$setTextBodyUIData$10(IndexUI.java:306)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

异常四：

java.lang.NullPointerException: Cannot invoke "javax.swing.text.View.getParent()" because the return value of "javax.swing.text.View.getView(int)" is null
    at java.desktop/javax.swing.text.View.setParent(View.java:336)
    at java.desktop/javax.swing.text.CompositeView.setParent(CompositeView.java:136)
    at java.desktop/javax.swing.text.FlowView.setParent(FlowView.java:306)
    at java.desktop/javax.swing.text.CompositeView.replace(CompositeView.java:192)
    at java.desktop/javax.swing.text.BoxView.replace(BoxView.java:182)
    at java.desktop/javax.swing.text.View.updateChildren(View.java:1129)
    at java.desktop/javax.swing.text.View.removeUpdate(View.java:749)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.removeUpdate(BasicTextUI.java:1728)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.removeUpdate(BasicTextUI.java:2011)
    at java.desktop/javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:284)
    at java.desktop/javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:651)
    at java.desktop/javax.swing.text.AbstractDocument.remove(AbstractDocument.java:619)
    at java.desktop/javax.swing.JEditorPane.setText(JEditorPane.java:1478)
    at com.nancheung.plugins.jetbrains.legadoreader.toolwindow.IndexUI.initTextBodyUI(IndexUI.java:277)
    at com.nancheung.plugins.jetbrains.legadoreader.toolwindow.IndexUI$2.mouseClicked(IndexUI.java:207)
    at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
    at java.desktop/java.awt.Component.processMouseEvent(Component.java:6660)
    at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
    at java.desktop/java.awt.Component.processEvent(Component.java:6422)
    at java.desktop/java.awt.Container.processEvent(Container.java:2266)
    at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
    at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
    at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4592)
    at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
    at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:699)
    at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
    at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:584)
    at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
    at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:584)
    at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
    at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1022)
    at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
    at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1022)
    at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
    at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

`

**Comment by nancheung** [comment]
好的，感谢反馈，我看一下
